version: '3'
services:

  # Nginx web server acting as a reverse proxy for "landing" and "api" services
  nginx:
    build:
      context: ./nginx
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - SUB_DOMAIN_NAME=${SUB_DOMAIN_NAME}
    container_name: res_nginx
    links:
      - landing
      - reserve
    ports:
      # Expose [HOST:CONTAINER]
      - "80"
      - "443"

  landing:
    build: ./landing
    container_name: res_landing
    command: npm start
    ports:
      - "5000"
    volumes:
      - ./landing:/usr/src/app

  reserve:
    depends_on:
      - reserve-db
    build: ./services/reserve
    container_name: res_service_reserve
    command: npm start
    ports:
      - "5001"
    links:
      - reserve-db
    volumes:
      - ./services/reserve:/usr/src/app

  reserve-db:
    # https://github.com/mvertes/docker-alpine-mongo
    build:
      context: ./mongodb
    container_name: reserve_db
    ports:
      - "27017"
    volumes:
      - reserve_db_data:/data/db

volumes:
  reserve_db_data:
